"""Train one information-safe REG selector checkpoint.

This is the focused, configurable counterpart to the historical sensitivity
launcher in ``example/run_small_rooms_example_hrl.py``.  It trains the complete
HRL agent because selector experience is generated by that controller, but its
primary artifact is the versioned ``selector_state_dict`` consumed by Track A.
"""

from __future__ import annotations

import argparse
import json
import os
import random
from pathlib import Path

import numpy as np
import torch

from example.Options.DeliverOption import DeliverOption
from example.Options.PickupRipeOption import PickupRipeOption
from example.Options.pickupOption import PickupOption
from example.Options.selector import StorageSelectOption
from example.Options.storeOption import StoreOption
from example.helper.tools import flat
from example.small_rooms_env import SmallRoomsEnv
from options_agent import CHECKPOINT_SCHEMA_VERSION, DQNAgent
from primitive_option import PrimitiveOption


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train one feature-v3 REG selector checkpoint"
    )
    parser.add_argument("--lambda", dest="lam", type=float, default=0.5)
    parser.add_argument("--mu", type=float, default=50.0)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--episodes", type=int, default=20)
    parser.add_argument("--max-steps", type=int, default=4000)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--lr-manager", type=float, default=5e-5)
    parser.add_argument("--lr-worker", type=float, default=3e-5)
    parser.add_argument("--update-every", type=int, default=100)
    parser.add_argument("--gamma", type=float, default=0.99)
    parser.add_argument("--tau-soft", type=float, default=1e-3)
    parser.add_argument("--grad-clip", type=float, default=5.0)
    parser.add_argument(
        "--selector-return-mode",
        choices=sorted(StorageSelectOption.RETURN_MODES),
        default=StorageSelectOption.RETURN_FULL_ENVIRONMENT,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/reg-selector-v3"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.episodes <= 0 or args.max_steps <= 0:
        raise ValueError("--episodes and --max-steps must be positive")
    hash_seed = os.environ.get("PYTHONHASHSEED")
    if hash_seed is None:
        raise RuntimeError(
            "PYTHONHASHSEED must be fixed before process startup because the "
            "environment stores controllers in sets; for example, run with "
            "PYTHONHASHSEED=0"
        )

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    output_dir = args.output_dir
    model_dir = output_dir / "models"
    datalog_dir = output_dir / "datalogs"
    tensorboard_dir = output_dir / "tensorboard"
    for directory in (model_dir, datalog_dir, tensorboard_dir):
        directory.mkdir(parents=True, exist_ok=True)

    env = SmallRoomsEnv(
        choose_storage=False,
        arrival_rate=args.lam,
        proc_mean=args.mu,
    )
    for action in env.get_action_space():
        env.options.add(PrimitiveOption(action, env))
    for option_class in (
        PickupOption,
        PickupRipeOption,
        DeliverOption,
        StoreOption,
        StorageSelectOption,
    ):
        if option_class is StorageSelectOption:
            option = option_class(env, return_mode=args.selector_return_mode)
        else:
            option = option_class(env)
        env.options.add(option)

    state_size = len(flat(env.reset()))
    primitive_count = sum(option.is_primitive for option in env.options)
    run_name = (
        f"reg_v{StorageSelectOption.FEATURE_VERSION}_"
        f"lam{args.lam}_mu{args.mu}_seed{args.seed}"
    )
    agent = DQNAgent(
        env=env,
        state_size=state_size,
        action_size=primitive_count,
        n_episodes=args.episodes,
        n_steps=args.max_steps,
        batch_size=args.batch_size,
        lr_manager=args.lr_manager,
        lr_worker=args.lr_worker,
        gamma=args.gamma,
        tau_soft=args.tau_soft,
        update_every=args.update_every,
        grad_clip=args.grad_clip,
        tb_logdir=str(tensorboard_dir),
        tb_run_name=run_name,
    )
    logs = agent.run(
        n_episodes=args.episodes,
        max_steps=args.max_steps,
        npz_dir=str(datalog_dir),
        model_dir=str(model_dir),
    )

    checkpoints = sorted(model_dir.glob("*_HRL.pth"), key=lambda p: p.stat().st_mtime)
    if not checkpoints:
        raise RuntimeError("training completed without writing a checkpoint")
    checkpoint = checkpoints[-1]
    payload = torch.load(checkpoint, map_location="cpu", weights_only=False)
    expected = {
        "checkpoint_schema_version": CHECKPOINT_SCHEMA_VERSION,
        "selector_feature_version": StorageSelectOption.FEATURE_VERSION,
    }
    for key, value in expected.items():
        if payload.get(key) != value:
            raise RuntimeError(
                f"invalid checkpoint metadata: {key}={payload.get(key)!r}, "
                f"expected {value!r}"
            )
    if not payload.get("selector_state_dict"):
        raise RuntimeError("checkpoint does not contain selector_state_dict")

    returns = np.asarray(logs["episode_returns"], dtype=float)
    successes = np.asarray(logs["episode_success"], dtype=float)
    summary = {
        "checkpoint": str(checkpoint.resolve()),
        "checkpoint_schema_version": payload["checkpoint_schema_version"],
        "selector_feature_version": payload["selector_feature_version"],
        "selector_return_definition": payload.get("selector_return_definition"),
        "selector_gamma": payload.get("selector_gamma"),
        "lambda": args.lam,
        "mu": args.mu,
        "seed": args.seed,
        "python_hash_seed": hash_seed,
        "episodes": args.episodes,
        "max_steps": args.max_steps,
        "mean_train_return": float(returns.mean()),
        "final_train_return": float(returns[-1]),
        "train_success_rate": float(successes.mean()),
        "final_train_success": float(successes[-1]),
        "selector_call_count": int(payload.get("selector_call_count", 0)),
        "selector_epsilon": float(payload.get("selector_eps", float("nan"))),
    }
    summary_path = output_dir / "training-summary.json"
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    print(f"Training summary: {summary_path}")


if __name__ == "__main__":
    main()
